export const PATHS = {
  root: '/',
  dev: '/dev',
  welcome: '/welcome',
  courses: '/course',
  courseCreate: '/course/create',
  courseDetail: '/course/:courseId',
  lessonsList: '/course/:courseId/lessons',
  lessonsCreate: '/course/:courseId/lesson/create',
  learning: '/course/:courseId/learn',
  lessonsDetail: '/course/:courseId/lesson/:lessonId',
  practiceLesson: '/course/:courseId/practice-lesson',
  practiceCourse: '/course/:courseId/practice-course',
  practice: '/course/:courseId/practice',
  studentsList: '/course/:courseId/students',
  courseSetting: '/course/:courseId/settings',
  rankList: '/course/:courseId/rank',
  myCourse: '/myCourse',
  myCourseLearning: '/myCourse/learning',
  myCourseTeaching: '/myCourse/teaching',
  profile: '/profile',
  dashboard: '/dashboard',
  signIn: '/login',
  signUp: '/signUp',
  logout: '/logout',
  forgotPassword: '/forgot-password',
  resetPassword: '/reset-password',
};
