export const PATHS = {
  root: '/',
  dev: '/dev',
  welcome: '/welcome',
  courses: '/course',
  courseCreate: '/course/create',
  courseDetail: '/course/:id',
  myCourse: '/myCourse',
  profile: '/profile',
  dashboard: '/dashboard',
  signIn: '/login',
  signUp: '/signUp',
  logout: '/logout',
  forgotPassword: '/forgot-password',
  resetPassword: '/reset-password',
};
